AuthenticationAndAuthorization/AuthenticationAndAuthorization/Models/EmailTemplateViewModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using EmailModule.Entity;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace AuthenticationAndAuthorization.Models
{
    public class EmailTemplateIndexViewModel
    {
        public long Id { get; set; }
        public string Type { get; set; }
       
    }

    public class EmailTemplateCreateViewModel
    {
        [Required(ErrorMessage ="Type is required")]
        public string Type { get; set; }
        private IList<string> TypeList { get; set; } = new List<string> {
        EmailTemplate.TypeRegistration,
        EmailTemplate.TypePasswordReset,
        EmailTemplate.TypeForgotPassword
        };

        public SelectList TypeSelectList => new SelectList(TypeList);
        [Required(ErrorMessage = "Template is required")]
        public string Template { get; set; }
    }

    public class EmailTemplateUpdateViewModel:EmailTemplateCreateViewModel
    {
        public long Id { get; set; }
    }

}

AuthenticationAndAuthorization/AuthenticationAndAuthorization/Controllers/EmailTemplateController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using AuthenticationAndAuthorization.Models;
using EmailModule.Repository;
using EmailModule.Service;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using NToastNotify;

namespace AuthenticationAndAuthorization.Controllers
{
    public class EmailTemplateController : Controller
    {
        private readonly EmailTemplateRepositoryInterface _templateRepo;
        private readonly ILogger<EmailTemplateController> _logger;
        private readonly EmailTemplateServiceInterface _emailTemplateService;
        private readonly IToastNotification _notification;
       
        public EmailTemplateController(EmailTemplateRepositoryInterface templateRepo,
            ILogger<EmailTemplateController> logger,
             EmailTemplateServiceInterface emailTemplateService,
             IToastNotification notification)
        {
            _templateRepo = templateRepo;
            _logger = logger;
            _emailTemplateService = emailTemplateService;
            _notification = notification;
        }
        public async Task<IActionResult> Index()
        {

            var emailTemplates = await _templateRepo.GetAllAsync().ConfigureAwait(true);
            var emailTemplateIndexModels = emailTemplates.Select(a => new EmailTemplateIndexViewModel
            {
            Id = a.Id,
            Type = a.Type
            });

            return View(emailTemplateIndexModels);
          
        }

        public IActionResult Create()
        {
            var emailTemplateCreateModel = new EmailTemplateCreateViewModel();
            return View(emailTemplateCreateModel);
        }

        [HttpPost]
        public async Task<IActionResult> Create(EmailTemplateCreateViewModel model)
        {
            try
            {
                var template = HttpUtility.HtmlDecode(model.Template);
                await _emailTemplateService.Create(model.Type, template);
                _notification.AddSuccessToastMessage("created successfully");
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {

                _logger.LogError(ex, ex.Message);
                _notification.AddErrorToastMessage(ex.Message);
            }
            return View(model);
        }


    }
}

AuthenticationAndAuthorization/AuthenticationAndAuthorization/Views/EmailTemplate/Create.cshtml
@model AuthenticationAndAuthorization.Models.EmailTemplateCreateViewModel
@using EmailModule.Entity
@{
}

<h2>Create Email Template</h2>

<div class="row">
    <div class="col-md-4">
        <div class="card">
            <div class="card-body card-rounded">
                <h4 class="card-title  card-title-dash">Keys</h4>

                @foreach (var key in EmailTemplate.TemplateVariables)
                {
                    <div class="list align-items-center border-bottom py-2">
                        <div class="wrapper w-100">
                            <p class="mb-2 font-weight-medium">
                                @key
                            </p>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>

    <div class="col-md-8">
        <form method="post" asp-area="" asp-controller="EmailTemplate" asp-action="Create">
            <div class="form-group">
                <label>Type</label>
                @(Html.DropDownListFor(a => a.Type, Model.TypeSelectList, "-select", new { @class = "form-control" }))
                @Html.ValidationMessageFor(a => a.Type)
            </div>

            <div class="form-group">
                <label>Template</label>
                <textarea id="editor" asp-for="Template"></textarea>
                @Html.ValidationMessageFor(a => a.Template)
            </div>


            <div class="form-group">
                <button type="submit" class="btn btn-primary">save </button>
            </div>

        </form>

    </div>

</div>

@section scripts
{
    <script>
      $(document).ready(function(){
        CKEDITOR.replace("editor")
    })
    </script>

}

AuthenticationAndAuthorization/AuthenticationAndAuthorization/Views/EmailTemplate/Index.cshtml
@model IEnumerable<AuthenticationAndAuthorization.Models.EmailTemplateIndexViewModel>
@{

}

<h2>Email Template</h2>
<div class="col-md-12">
    <div class=" form-group">
        <a class="btn btn-primary btn-icon-text" asp-area="" asp-controller="EmailTemplate" asp-action="Create"><i class="ti-plus btn-icon-prepend"></i> Add</a>
    </div>
    <table id="templateTable" class=" table table-bordered ">
        <thead>
        <tr>
            <th>Id</th>
            <th>Type</th>

            <th>Action</th>
        </tr>
        </thead>
        <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td > @item.Id</td>
                <td > @item.Type</td>

                <td>
                    <a class=" btn btn-info btn-sm">Edit</a>
                    <a class=" btn btn-secondary btn-sm"target="_blank" asp-area="" asp-controller="EmailTemplate" asp-action="Update" asp-route-id="@item.Id">Update</a>
                    <a class=" btn btn-info btn-sm"target="_blank" asp-area="" asp-controller="EmailTemplate" asp-action="Preview" asp-route-roleId="@item.Id">Preview</a>
                </td>
            </tr>
        }
        </tbody>
    </table>
</div>