AuthenticationAndAuthorization/AuthenticationAndAuthorization/Areas/User/Controllers/ChangePasswordController.cs
using System;
using System.Threading.Tasks;
using AuthenticationAndAuthorization.Areas.User.ViewModel;
using AuthenticationAndAuthorization.Extensions;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using NToastNotify;
using UserModule.Exceptions;

namespace AuthenticationAndAuthorization.Areas.User.Controllers
{
    [Area("User")]
    public class ChangePasswordController : Controller
    {
        private readonly UserManager<UserModule.Entity.User> _userManager;
        private readonly ILogger<ChangePasswordController> _logger;
        private readonly IToastNotification _notify;
        public ChangePasswordController(UserManager<UserModule.Entity.User> userManager,
            ILogger<ChangePasswordController> logger,
            IToastNotification notify)
        {
            _logger = logger;
            _userManager = userManager;
            _notify = notify;
        }
        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Index(ChangePasswordViewModel model)
        {
            try
            {
                var userId = this.GetCurrentUserId();
                var user = await _userManager.FindByIdAsync(userId) ?? throw new UserNotFoundException();
                if (ModelState.IsValid)
                {
                    var result = await _userManager.ChangePasswordAsync(user, model.OldPasword, model.NewPassword).ConfigureAwait(true);
                    if(result.Succeeded)
                    {
                        _notify.AddSuccessToastMessage("Password Changed Successfully");
                        return RedirectToAction("Index", "Home", new { area = "" });
                    }
                    foreach(var error in result.Errors)
                    {
                        ModelState.AddModelError("error", error.Description);
                    }
                }
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, ex.Message);
                _notify.AddErrorToastMessage(ex.Message);
            }
            return View(model);
        }

        public async Task<IActionResult> AddPassword()
        {
            try
            {
                var user = await this.GetCurrentUser();
                var hasPassword = await _userManager.HasPasswordAsync(user);
                if (hasPassword) return RedirectToAction(nameof(Index));
                return View();
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, ex.Message);
                _notify.AddErrorToastMessage(ex.Message);
            }
            return RedirectToAction("Index", "Home", new { area = "" });
        }

        [HttpPost]
        public async Task<IActionResult> AddPassword(AddPasswordViewModel model)
        {
            try
            {
                if(ModelState.IsValid)
                {
                    var userId =  this.GetCurrentUserId();
                    var user = await _userManager.FindByIdAsync(userId) ?? throw new UserNotFoundException();
                    var isSucceded = await _userManager.AddPasswordAsync(user, model.ConfirmPassword);
                    if (isSucceded.Succeeded)
                    {
                        _notify.AddSuccessToastMessage("Password added Successfully");
                        return RedirectToAction("Index", "Home",new { area = "" });
                    }

                }
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, ex.Message);
                _notify.AddErrorToastMessage(ex.Message);
            }
            return View(model);
        }
    }
}

AuthenticationAndAuthorization/AuthenticationAndAuthorization/Areas/User/Controllers/RoleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using AuthenticationAndAuthorization.Areas.User.ViewModel;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using NToastNotify;
using UserModule.Dto.Role;
using UserModule.Exceptions;
using UserModule.PermissionHandler;
using UserModule.Service;

namespace AuthenticationAndAuthorization.Areas.User.Controllers
{
    [Area("User")]
    
    public class RoleController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly UserManager<UserModule.Entity.User> _userManager;
        private readonly RoleServiceInterface _roleService;
        private readonly ILogger<RoleController> _logger;
        private readonly IToastNotification _notify;
        public RoleController(RoleManager<IdentityRole> roleManager,
          RoleServiceInterface roleService,
          ILogger<RoleController> logger,
          IToastNotification notify,
          UserManager<UserModule.Entity.User> userManager)
        {
            _roleManager = roleManager;
            _roleService = roleService;
            _logger = logger;
            _notify = notify;
            _userManager = userManager;
        }
        public IActionResult Index()
        {
            var roles = _roleManager.Roles;
            var roleIndexViewModels = new List<RoleIndexViewModel>();
            var i = 1;
            foreach (var role in roles)
            {
                roleIndexViewModels.Add(new RoleIndexViewModel
                {
                    Sno = i,
                    Id = role.Id,
                    Name = role.Name,

                });
                i++;
              
            }
            return View(roleIndexViewModels);
        }

        public async Task<IActionResult> Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(RoleViewModel model)
        {
            try
            {
                var dto = new RoleDto() { RoleName = model.RoleName };
                await _roleService.Create(dto);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                _notify.AddErrorToastMessage(ex.Message);
                _logger.LogError(ex, ex.Message);
            }
            return View(model);
        }

        public async Task<IActionResult> AssignUser(string roleId)
        {
            try
            {
                var role = await _roleManager.FindByIdAsync(roleId) ?? throw new Exception("Role Not Found");
                var users =  await _userManager.Users.ToListAsync();
                var assignUserIndexViewModel = new AssignRoleToUserIndexViewModel();
                assignUserIndexViewModel.RoleId = roleId;
                assignUserIndexViewModel.RoleName = role.Name;
                foreach(var user in users)
                {
                    var userModel = new AssignRoleToUserViewModel
                    {
                        UserId = user.Id,
                        Name = user.UserName
                    };
                  
                    if( await _userManager.IsInRoleAsync(user, role.Name))
                    {
                        userModel.IsSelected = true;
                    }
                    else
                    {
                        userModel.IsSelected = false;
                    }
                    assignUserIndexViewModel.Users.Add(userModel);
                }
                return View(assignUserIndexViewModel);
            }
            catch (Exception ex)
            {

                _notify.AddErrorToastMessage(ex.Message);
                _logger.LogError(ex, ex.Message);
            }
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public async Task<IActionResult> AssignUser(AssignRoleToUserIndexViewModel model)
        {
            try
            {
                var assignUserToRoleDto = new AssignUsersToRoleDto()
                {
                    RoleId = model.RoleId
                };
                foreach(var user in model.Users)
                {
                    assignUserToRoleDto.Users.Add(new AssignUserDto
                    {
                        UserId = user.UserId,
                        IsSelected = user.IsSelected
                    });
                }
              await   _roleService.AssingUser(assignUserToRoleDto);
                _notify.AddSuccessToastMessage("Users Added");
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {

                _notify.AddErrorToastMessage(ex.Message);
                _logger.LogError(ex, ex.Message);
            }
            return View(model);
        }
        public async Task<IActionResult> Edit(string roleId)
        {
            try
            {
                var role = await _roleManager.FindByIdAsync(roleId) ?? throw new RoleNotFoundException();
                var roleEditViewModel = new RoleEditViewModel() { 
                Id = roleId,
                Name = role.Name
                };
                return View(roleEditViewModel);
            }
            catch (Exception ex)
            {
                _notify.AddErrorToastMessage(ex.Message);
                _logger.LogError(ex, ex.Message);            
            }
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Edit(RoleEditViewModel model)
        {
            try
            {
                
            }
            catch (Exception ex)
            {

                _notify.AddErrorToastMessage(ex.Message);
                _logger.LogError(ex, ex.Message);
            }
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> AssignPermission(string roleId)
        {
            try
            {

                var role = await _roleManager.FindByIdAsync(roleId) ?? throw new RoleNotFoundException();
                var roleClaims = await _roleManager.GetClaimsAsync(role);
                var permissionIndexModel = new RolePermissionViewModel() { 
                RoleId = roleId,
                RoleName = role.Name
                };

                foreach(var claim in Permission.Permissions)
                {
                    var claimModel = new AssignPermissionViewModel {
                    Permission = claim
                    };
                    if(roleClaims.Any(a=>a.Value == claim))
                    {
                        claimModel.IsSelected = true;
                    }
                    permissionIndexModel.Permissions.Add(claimModel);
                }
                return View(permissionIndexModel);
            }
            catch (Exception ex)
            {
                _notify.AddErrorToastMessage(ex.Message);
                _logger.LogError(ex, ex.Message);
            }
            return RedirectToAction(nameof(Index));
        }
        [HttpPost]
        public async Task<IActionResult> AssignPermission(RolePermissionViewModel model)
        {
            try
            {
                var role = await _roleManager.FindByIdAsync(model.RoleId) ?? throw new RoleNotFoundException();
                var claims = await _roleManager.GetClaimsAsync(role);
                foreach(var claim in claims)
                {
                    var result = await _roleManager.RemoveClaimAsync(role, claim);
                    if (!result.Succeeded) throw new Exception("Error in setting permission");
                }
                foreach(var permission in model.Permissions)
                {
                    if(permission.IsSelected == true)
                    {
                        await _roleManager.AddClaimAsync(role, new Claim(Permission.PermissionClaimType,permission.Permission));
                    }
                }

               
              
            }
            catch (Exception ex)
            {
                _notify.AddErrorToastMessage(ex.Message);
                _logger.LogError(ex, ex.Message);
            }
            return RedirectToAction(nameof(Index));
        }
        

    }
}

AuthenticationAndAuthorization/AuthenticationAndAuthorization/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title> Authentication & Authorization~/ </title>
    <link rel="stylesheet" href="~/vendors/feather/feather.css">
    <link rel="stylesheet" href="~/vendors/mdi/css/materialdesignicons.min.css">
    <link rel="stylesheet" href="~/vendors/ti-icons/css/themify-icons.css">
    <link rel="stylesheet" href="~/vendors/typicons/typicons.css">
    <link rel="stylesheet" href="~/vendors/simple-line-icons/css/simple-line-icons.css">
    <link rel="stylesheet" href="~/vendors/css/vendor.bundle.base.css">
    <link rel="stylesheet" href="~/vendors/datatables.net-bs4/dataTables.bootstrap4.css">
    <link rel="stylesheet" href="~/js/select.dataTables.min.css">
    <link rel="stylesheet" href="~/css/vertical-layout-light/style.css">
    <link rel="stylesheet" href="~/css/site.css">
    <link rel="shortcut icon" href="~/images/favicon.png"/>
</head>
<body class="sidebar-dark">
@await Html.PartialAsync("_header")
<div class="container-fluid page-body-wrapper">


    @await Html.PartialAsync("_menubar")

    <div class="main-panel">
        <div class="content-wrapper">
            @RenderBody()
        </div>
        @await Html.PartialAsync("_footer")
    </div>

    @await Component.InvokeAsync("NToastNotify")
</div>

<script src="~/vendors/js/vendor.bundle.base.js"></script>
<script src="~/vendors/chart.js/Chart.min.js"></script>
<script src="~/vendors/bootstrap-datepicker/bootstrap-datepicker.min.js"></script>
<script src="~/vendors/progressbar.js/progressbar.min.js"></script>
<script src="~/js/off-canvas.js"></script>
<script src="~/js/hoverable-collapse.js"></script>
<script src="~/js/template.js"></script>
<script src="~/js/settings.js"></script>
<script src="~/js/todolist.js"></script>~/
<script src="~/js/jquery.cookie.js" type="text/javascript"></script>
<script src="~/js/dashboard.js"></script>
<script src="~/js/Chart.roundedBarCharts.js"></script>

@* <script src="~/lib/jquery/dist/jquery.min.js" asp-append-version="true"></script> *@
<script src="~/ckeditor/ckeditor.js" asp-append-version="true"></script>
<script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js" asp-append-version="true"></script>

@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

AuthenticationAndAuthorization/AuthenticationAndAuthorization/Views/Shared/_footer.cshtml
@{
    Layout = null;
}
    
<footer class="footer">
    <div class="d-sm-flex justify-content-center justify-content-sm-between">
        <span class="text-muted text-center text-sm-left d-block d-sm-inline-block"> Authentication & Authorization.</span>
        <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center">Copyright © 2021. All rights reserved.</span>
    </div>
</footer>

AuthenticationAndAuthorization/AuthenticationAndAuthorization/Views/Shared/_header.cshtml
<nav class="navbar default-layout col-lg-12 col-12 p-0 fixed-top d-flex align-items-top flex-row">
      <div class="text-center navbar-brand-wrapper d-flex align-items-center justify-content-start">
        <div class="me-3">
          <button class="navbar-toggler navbar-toggler align-self-center" type="button" data-bs-toggle="minimize">
            <span class="icon-menu"></span>
          </button>
        </div>
        <div>
          <a class="navbar-brand brand-logo" href="#">
            <img src="~/images/logo.svg" alt="logo" />
          </a>
          <a class="navbar-brand brand-logo-mini" href="#">
            <img src="~/images/logo-mini.svg" alt="logo" />
          </a>
        </div>
      </div>
      <div class="navbar-menu-wrapper d-flex align-items-top"> 
        <ul class="navbar-nav">
          <li class="nav-item font-weight-semibold d-none d-lg-block ms-0">
            <h1 class="welcome-text">Authentication & Authorization</h1>
          </li>
        </ul>
        <ul class="navbar-nav ms-auto">
        
         
          <li class="nav-item">
            <form class="search-form" action="#">
              <i class="icon-search"></i>
              <input type="search" class="form-control" placeholder="Search Here" title="Search here">
            </form>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link count-indicator" id="notificationDropdown" href="#" data-bs-toggle="dropdown">
              <i class="icon-mail icon-lg"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-right navbar-dropdown preview-list pb-0" aria-labelledby="notificationDropdown">
              <a class="dropdown-item py-3 border-bottom">
                <p class="mb-0 font-weight-medium float-left">You have 4 new notifications </p>
                <span class="badge badge-pill badge-primary float-right">View all</span>
              </a>
              <a class="dropdown-item preview-item py-3">
                <div class="preview-thumbnail">
                  <i class="mdi mdi-alert m-auto text-primary"></i>
                </div>
                <div class="preview-item-content">
                  <h6 class="preview-subject fw-normal text-dark mb-1">Application Error</h6>
                  <p class="fw-light small-text mb-0"> Just now </p>
                </div>
              </a>
              <a class="dropdown-item preview-item py-3">
                <div class="preview-thumbnail">
                  <i class="mdi mdi-settings m-auto text-primary"></i>
                </div>
                <div class="preview-item-content">
                  <h6 class="preview-subject fw-normal text-dark mb-1">Settings</h6>
                  <p class="fw-light small-text mb-0"> Private message </p>
                </div>
              </a>
              <a class="dropdown-item preview-item py-3">
                <div class="preview-thumbnail">
                  <i class="mdi mdi-airballoon m-auto text-primary"></i>
                </div>
                <div class="preview-item-content">
                  <h6 class="preview-subject fw-normal text-dark mb-1">New user registration</h6>
                  <p class="fw-light small-text mb-0"> 2 days ago </p>
                </div>
              </a>
            </div>
          </li>
          <li class="nav-item dropdown"> 
            <a class="nav-link count-indicator" id="countDropdown" href="#" data-bs-toggle="dropdown" aria-expanded="false">
              <i class="icon-bell"></i>
              <span class="count"></span>
            </a>
            <div class="dropdown-menu dropdown-menu-right navbar-dropdown preview-list pb-0" aria-labelledby="countDropdown">
              <a class="dropdown-item py-3">
                <p class="mb-0 font-weight-medium float-left">You have 7 unread mails </p>
                <span class="badge badge-pill badge-primary float-right">View all</span>
              </a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item preview-item">
                <div class="preview-thumbnail">
                  <img src="~/images/faces/face10.jpg" alt="image" class="img-sm profile-pic">
                </div>
                <div class="preview-item-content flex-grow py-2">
                  <p class="preview-subject ellipsis font-weight-medium text-dark">Marian Garner </p>
                  <p class="fw-light small-text mb-0"> The meeting is cancelled </p>
                </div>
              </a>
              <a class="dropdown-item preview-item">
                <div class="preview-thumbnail">
                  <img src="~/images/faces/face12.jpg" alt="image" class="img-sm profile-pic">
                </div>
                <div class="preview-item-content flex-grow py-2">
                  <p class="preview-subject ellipsis font-weight-medium text-dark">David Grey </p>
                  <p class="fw-light small-text mb-0"> The meeting is cancelled </p>
                </div>
              </a>
              <a class="dropdown-item preview-item">
                <div class="preview-thumbnail">
                  <img src="~/images/faces/face1.jpg" alt="image" class="img-sm profile-pic">
                </div>
                <div class="preview-item-content flex-grow py-2">
                  <p class="preview-subject ellipsis font-weight-medium text-dark">Travis Jenkins </p>
                  <p class="fw-light small-text mb-0"> The meeting is cancelled </p>
                </div>
              </a>
            </div>
          </li>
          <li class="nav-item dropdown d-none d-lg-block user-dropdown">
            <a class="nav-link" id="UserDropdown" href="#" data-bs-toggle="dropdown" aria-expanded="false">
              <img class="img-xs rounded-circle" src="~/images/faces/face8.jpg" alt="Profile image"> </a>
            <div class="dropdown-menu dropdown-menu-right navbar-dropdown" aria-labelledby="UserDropdown">
              <div class="dropdown-header text-center">
                <img class="img-md rounded-circle" src="~/images/faces/face8.jpg" alt="Profile image">
                <p class="mb-1 mt-3 font-weight-semibold">@User.Identity.Name</p>
              
              </div>
              <a class="dropdown-item" asp-area="User" asp-controller="ChangePassword" asp-action="Index"><i class="dropdown-item-icon mdi mdi-account-outline text-primary me-2"></i> Change Password <span class="badge badge-pill badge-danger">1</span></a>
                 <a class="dropdown-item" asp-area=""  asp-controller="account" asp-action="LogOut"><i class="dropdown-item-icon mdi mdi-power text-primary me-2"></i>Sign Out</a>
            </div>
          </li>
        </ul>
        <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-bs-toggle="offcanvas">
          <span class="mdi mdi-menu"></span>
        </button>
      </div>
    </nav>

AuthenticationAndAuthorization/AuthenticationAndAuthorization/Views/Shared/_menuBar.cshtml
<nav class="sidebar sidebar-offcanvas" id="sidebar">
    <ul class="nav">
        <li class="nav-item">
            <a class="nav-link" href="/">
                <i class="mdi mdi-grid-large menu-icon"></i>
                <span class="menu-title">Dashboard</span>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/activitylog">
                <i class="mdi mdi-bag-personal menu-icon"></i>
                <span class="menu-title">Activity Log</span>
            </a>
        </li>
          <li class="nav-item">
            <a class="nav-link" href="/auditLog">
                <i class="mdi mdi-bag-personal menu-icon"></i>
                <span class="menu-title">Audit Log</span>
            </a>
        </li>

        <li class="nav-item">
            <a class="nav-link" href="/emailtemplate">
                <i class="mdi mdi-email menu-icon"></i>
                <span class="menu-title">Email Template</span>
            </a>
        </li>

         <li class="nav-item">
            <a class="nav-link" asp-area="user" asp-controller="Role" asp-action="Index">
                <i class="mdi mdi-account-check menu-icon"></i>
                <span class="menu-title">Role</span>
            </a>
        </li>  
        <li class="nav-item">
            <a class="nav-link" asp-area="user" asp-controller="User" asp-action="Index">
                <i class="mdi mdi-account menu-icon"></i>
                <span class="menu-title">User</span>
            </a>
        </li>

        @* <li class="nav-item"> *@
        @*   <a class="nav-link" data-bs-toggle="collapse" href="#ui-basic" aria-expanded="false" aria-controls="ui-basic"> *@
        @*     <i class="menu-icon mdi mdi-floor-plan"></i> *@
        @*     <span class="menu-title">UI Elements</span> *@
        @*     <i class="menu-arrow"></i>  *@
        @*   </a> *@
        @*   <div class="collapse" id="ui-basic"> *@
        @*     <ul class="nav flex-column sub-menu"> *@
        @*       <li class="nav-item"> <a class="nav-link" href="pages/ui-features/buttons.html">Buttons</a></li> *@
        @*       <li class="nav-item"> <a class="nav-link" href="pages/ui-features/dropdowns.html">Dropdowns</a></li> *@
        @*       <li class="nav-item"> <a class="nav-link" href="pages/ui-features/typography.html">Typography</a></li> *@
        @*     </ul> *@
        @*   </div> *@
        @* </li> *@
    </ul>
</nav>